server.use-forward-headers: true
server:
  port: 7777

line.bot:
  handler.path: /callback
  channel-token: ${your-channel-token-1}
  channel-secret: ${your-channel-secret-1}
  list :
    - channel-token: ${your-channel-token-2}
      channel-secret: ${your-channel-secret-2}

